//! forger's differential oracle, with smugglr's own forward apply as the
//! transformation.
//!
//! Everything forger proved before this file existed, it proved about
//! transformations forger itself wrote. Each known-defect case reproduces a
//! defect's *mechanism* by hand and confirms the oracle notices, which is the
//! right way to validate a harness and says nothing about the engine. "forger
//! would have caught #341" was an argument from a reconstruction until
//! something pointed it at the real rebuild. This is that something.
//!
//! The closure handed to [`differential`] calls
//! [`smugglr_core::migrate::driver::apply_migration`] -- the composing forward
//! apply the CLI drives, which verifies the manifest checksum, ensures the
//! ledger schema, assigns and elects a version, lints, and runs the real
//! `migrate::apply::apply_ops` with the pre-image capturer bound to its
//! write-ahead hook. No SQL in this file is executed against the transformed
//! arm; every statement that reaches it was generated by migrate.
//!
//! # The dependency direction
//!
//! forger depends on no smugglr crate and never will
//! (`scripts/check-forger-boundary.py`). This file is the other half of that
//! rule: smugglr's tests depend on forger, dev-only, by path. It is what makes
//! the exclusion set a caller parameter rather than a list forger maintains --
//! [`SyncConfig::default().exclude_tables`] is `config::default_exclude_tables()`
//! reached through the engine's own public surface, and it contains
//! `_smugglr_migrations`, which the driver creates in the transformed arm and
//! which nothing creates in the other. Hand in nothing and every run reports
//! the ledger as a divergence; hand in the engine's list and the same run is
//! silent. forger learns the name from the caller either way.
//!
//! # The two paths, and which defects each one reaches
//!
//! There are two tests here because the apply engine has two ways to change a
//! table, and only one of them was ever broken.
//!
//! [`the_real_apply_path_preserves_every_trait_it_migrates_over`] is additive --
//! `ADD COLUMN` and `CREATE TABLE`. Neither reaches
//! `migrate::apply::rebuild_dropping_column`, the only path that *reconstructs*
//! a table rather than asking SQLite to alter it. **Do not read a green run
//! there as coverage of the rebuild**; it was measured green on all eight
//! traits while the rebuild was red on three.
//!
//! [`the_rebuild_path_preserves_the_referential_actions_it_reconstructs`] is the
//! other one, added with the fix for **#341**. `reconstruct_foreign_keys` read
//! five of `foreign_key_list`'s eight columns, so a rebuilt `cascade_child` came
//! back holding its foreign key and not its `ON DELETE CASCADE` -- present and
//! inert. That test is the red-to-green flip: against this same wiring before
//! the fix, the probe reported *"deleting keeper.id = 1 was refused (FOREIGN KEY
//! constraint failed), and a child declared ON DELETE CASCADE does not refuse
//! it"*.
//!
//! Reaching the rebuild takes deliberate setup, which is worth knowing before
//! writing a third test here: `drop_column` tries the direct `ALTER` first and
//! rebuilds only when SQLite refuses, so the dropped column has to be one SQLite
//! will refuse -- hence [`REBUILD_FORCER`] being `UNIQUE`.
//!
//! # What is still not reached
//!
//! * **#342** -- `PRAGMA table_info` does not return generated columns at all,
//!   so a rebuild never sees them and cannot copy them.
//!   [`Trait::GeneratedVirtual`] and [`Trait::GeneratedStored`]. Open. The
//!   rebuild test above drops a column from the two tables carrying foreign
//!   keys, and the generated columns live on other tables, so no rebuild in this
//!   file touches one. A manifest that rebuilt `virtual_generated` is red today.
//! * **The destructive lane.** Both manifests declare `preimage: None` and
//!   neither op is classified destructive, so the pre-image capturer bound to
//!   the apply loop's write-ahead hook captures nothing. `DROP COLUMN` on a
//!   column nothing reads does not exercise it. That is #378.
//! * **`ON UPDATE` beyond `CASCADE`, and `RESTRICT`.** The referential-action
//!   probe now covers both `ON DELETE` and `ON UPDATE` (#374 added the update
//!   arm, and the rebuild test drops a column from `updating_child` so the real
//!   engine reconstructs that key too). `SET NULL` and `SET DEFAULT` are
//!   declared by no case on either side (#384), and `RESTRICT` is behaviourally
//!   identical to the `NO ACTION` default under immediate enforcement. forger's
//!   own boundary output states all of it.

use rusqlite::Connection;

use smugglr_core::config::SyncConfig;
use smugglr_core::migrate::driver::{apply_migration, ApplyOptions};
use smugglr_core::migrate::ledger::Election;
use smugglr_core::migrate::{
    ChecksummedManifest, ClassifiedOp, Column, ColumnKind, Constraint, Flags, Manifest, Op,
};

use smugglr_forger::census::every_trait_schema;
use smugglr_forger::error::BoxError;
use smugglr_forger::fixture::Backing;
use smugglr_forger::oracle::{differential, Outcome};
use smugglr_forger::registry::Combination;
use smugglr_forger::schema::builder::{schema, table};
// Renamed on import: `smugglr_core::migrate::Column` is a manifest op's column
// and this one is a schema model's. Two `Column`s in one file is a reader
// tripping over which layer they are in.
use smugglr_forger::schema::{Column as ForgedColumn, ColumnConstraint, ColumnType, Schema, Trait};

/// The table in forger's every-trait schema that carries the foreign key with a
/// referential action -- the #341 table. The migration adds a column to *this*
/// one rather than to an inert table, so the apply runs over a table whose
/// behaviour the oracle is watching.
const FK_TABLE: &str = "cascade_child";

/// The column the migration adds. Named for what it is, since it lands in a
/// schema whose other column names are forger's.
const ADDED_COLUMN: &str = "migration_note";

/// The table the migration creates. It carries no trait; it is here so the
/// oracle's table inventory has something to compare that only exists because
/// migrate ran.
const CREATED_TABLE: &str = "migration_audit";

// ---------------------------------------------------------------------------
// The test
// ---------------------------------------------------------------------------

/// A real migration, applied by the real driver, over a schema carrying all
/// eight traits.
///
/// Both backings, because the oracle's arms are stood up per backing and the
/// CLI's apply reaches a file while these assertions are cheap enough to make
/// twice.
#[test]
fn the_real_apply_path_preserves_every_trait_it_migrates_over() {
    for backing in Backing::ALL {
        let start = every_trait_schema();
        let target = after_the_migration(&start);
        let sealed = the_migration();

        // The engine's own list, reached through the engine's own public
        // surface: `SyncConfig::default().exclude_tables` *is*
        // `config::default_exclude_tables()`.
        let ignore = SyncConfig::default().exclude_tables;

        let mut applied = Vec::new();
        let mut transform = |conn: &mut Connection| -> Result<(), BoxError> {
            applied.push(apply_migration(conn, &sealed, &ApplyOptions::default())?);
            Ok(())
        };

        let report = differential(backing, &start, &target, &mut transform, &ignore)
            .unwrap_or_else(|error| panic!("{backing:?}: the migration did not run: {error}"));

        // A migration that did not apply would leave both arms holding on every
        // trait, so the run has to be shown to have happened before the silence
        // is read as a result. The election is the driver's own word for it.
        let outcome = match applied.as_slice() {
            [outcome] => outcome,
            other => panic!("{backing:?}: the transformation ran {} times", other.len()),
        };
        assert_eq!(
            outcome.election,
            Election::Won,
            "{backing:?}: the driver has to have won its election, or it applied nothing"
        );
        assert_eq!(
            outcome.classifications.len(),
            sealed.manifest.up.len(),
            "{backing:?}: every op should have been linted and applied"
        );

        // Two arms that broke identically do not diverge, so "no divergence" is
        // also what a bad target schema or a mislocated probe produces. Without
        // this, every comparison below is an agreement between two wrong
        // answers.
        assert!(
            report.baseline_is_sound(),
            "{backing:?}: these did not hold in the arm built from the target schema, so nothing \
             compared against it means anything: {:?}",
            report.unsound_baseline()
        );

        for observed in &report.traits {
            assert_eq!(
                observed.transformed,
                Outcome::Held,
                "{backing:?}: {:?} did not hold after the real apply",
                observed.kind
            );
        }

        assert_eq!(
            report.divergences(),
            Vec::new(),
            "{backing:?}: the migrated database and the one built from the target schema \
             answered differently"
        );

        // Named rather than left to the loop above, because this is the trait
        // the additive path is being claimed for: the table the migration
        // altered is the table whose cascade the probe deletes through.
        assert_eq!(
            report.for_trait(Trait::ForeignKeyWithAction).transformed,
            Outcome::Held,
            "{backing:?}: ADD COLUMN on {FK_TABLE:?} lost its referential action"
        );
    }
}

// ---------------------------------------------------------------------------
// The rebuild path (#341)
// ---------------------------------------------------------------------------

/// The table carrying the `ON UPDATE CASCADE` key, since #374 gave the case one.
const UPDATE_FK_TABLE: &str = "updating_child";

/// A column that exists only to make the direct `ALTER TABLE DROP COLUMN`
/// refuse, so the op falls through to the rebuild.
///
/// `drop_column` tries the direct ALTER first and rebuilds only when SQLite
/// turns it down (`apply.rs:497-507`), and forger's case schema has nothing on
/// these tables that would refuse. Dropping an ordinary column here would test
/// the path that was never broken -- #379 measured the direct drop green on all
/// eight traits while the rebuild was red on three.
const REBUILD_FORCER: &str = "rebuild_forcer";

/// The rebuild reconstructs the referential actions it used to drop.
///
/// This is #341's red-to-green flip, and it is deliberately *not* asserting
/// reconstructed DDL text: the defect produced a key that was present and
/// inert, so `foreign_key_list` reporting a row proves nothing. What is asserted
/// is that forger's probe -- which deletes a parent and moves a key and reads
/// what happened to the children -- holds after the real engine rebuilt both
/// tables.
///
/// Against the same wiring before the fix, `ForeignKeyWithAction` reported:
/// *"deleting keeper.id = 1 was refused (FOREIGN KEY constraint failed), and a
/// child declared ON DELETE CASCADE does not refuse it -- the action was
/// reconstructed as something else, or dropped, which leaves NO ACTION"*.
#[test]
fn the_rebuild_path_preserves_the_referential_actions_it_reconstructs() {
    for backing in Backing::ALL {
        let start = every_trait_schema_with_a_rebuild_forcer();
        let target = every_trait_schema();
        let sealed = the_rebuilding_migration();

        let ignore = SyncConfig::default().exclude_tables;

        let mut applied = Vec::new();
        let mut transform = |conn: &mut Connection| -> Result<(), BoxError> {
            applied.push(apply_migration(conn, &sealed, &ApplyOptions::default())?);
            Ok(())
        };

        let report = differential(backing, &start, &target, &mut transform, &ignore)
            .unwrap_or_else(|error| panic!("{backing:?}: the migration did not run: {error}"));

        let outcome = match applied.as_slice() {
            [outcome] => outcome,
            other => panic!("{backing:?}: the transformation ran {} times", other.len()),
        };
        assert_eq!(
            outcome.election,
            Election::Won,
            "{backing:?}: the driver has to have won its election, or it applied nothing"
        );

        assert!(
            report.baseline_is_sound(),
            "{backing:?}: the arm built from the target schema did not hold, so nothing compared \
             against it means anything: {:?}",
            report.unsound_baseline()
        );

        // Named first and separately, because this trait is the one the fix is
        // about and a loop that happened to skip it would still read as green.
        assert_eq!(
            report.for_trait(Trait::ForeignKeyWithAction).transformed,
            Outcome::Held,
            "{backing:?}: the rebuild lost a referential action -- #341"
        );

        for observed in &report.traits {
            assert_eq!(
                observed.transformed,
                Outcome::Held,
                "{backing:?}: {:?} did not hold after the real rebuild",
                observed.kind
            );
        }

        assert_eq!(
            report.divergences(),
            Vec::new(),
            "{backing:?}: the rebuilt database and the one built from the target schema answered \
             differently"
        );
    }
}

/// The every-trait schema with a `UNIQUE` column on each table carrying a
/// referential action, so dropping it forces the rebuild.
///
/// `UNIQUE` rather than an index, because the column has to be refused by the
/// direct `ALTER` and has to be droppable without taking a trait with it. It is
/// nullable and nothing seeds it, so it is invisible to every probe.
fn every_trait_schema_with_a_rebuild_forcer() -> Schema {
    let mut start = every_trait_schema();
    for name in [FK_TABLE, UPDATE_FK_TABLE] {
        let table = start
            .tables
            .iter_mut()
            .find(|existing| existing.name == name)
            .unwrap_or_else(|| panic!("the every-trait schema carries {name:?}"));
        table.columns.push(ForgedColumn {
            name: REBUILD_FORCER.into(),
            decl_type: Some(ColumnType::Text),
            constraints: vec![ColumnConstraint::Unique(None)],
        });
    }
    start
        .validate()
        .expect("the pre-migration schema is one SQLite accepts");
    start
}

/// Two `DROP COLUMN`s, each landing on a table whose foreign key carries an
/// action, and each forced through the rebuild by the column being `UNIQUE`.
///
/// The target schema is `every_trait_schema()` itself rather than a third
/// description: this migration removes exactly what
/// [`every_trait_schema_with_a_rebuild_forcer`] added, so arriving back at the
/// registry's own schema is the strongest available statement that it arrived
/// where it claimed.
fn the_rebuilding_migration() -> ChecksummedManifest {
    ChecksummedManifest::seal(Manifest {
        version: 1,
        target_schema: "opaque".into(),
        up: vec![FK_TABLE, UPDATE_FK_TABLE]
            .into_iter()
            .map(|table| {
                ClassifiedOp::new(Op::DropColumn {
                    table: table.into(),
                    column: REBUILD_FORCER.into(),
                })
            })
            .collect(),
        down: Vec::new(),
        preimage: None,
        flags: Flags::default(),
        author: None,
    })
    .expect("the manifest seals")
}

// ---------------------------------------------------------------------------
// The migration
// ---------------------------------------------------------------------------

/// The manifest, sealed exactly as the CLI would read one off disk.
///
/// `version: 1` is the generator's hardcoded value and the driver overrides it;
/// `target_schema` is opaque for 0.5.0. Both ops are structurally additive, so
/// the lint passes them and no pre-image is required.
fn the_migration() -> ChecksummedManifest {
    ChecksummedManifest::seal(Manifest {
        version: 1,
        target_schema: "opaque".into(),
        up: vec![
            ClassifiedOp::new(Op::AddColumn {
                table: FK_TABLE.into(),
                column: Column {
                    name: ADDED_COLUMN.into(),
                    kind: ColumnKind::Text,
                    constraints: Vec::new(),
                    tags: Vec::new(),
                },
            }),
            ClassifiedOp::new(Op::CreateTable {
                table: CREATED_TABLE.into(),
                columns: vec![
                    Column {
                        name: "id".into(),
                        kind: ColumnKind::Int,
                        constraints: vec![Constraint::Pk],
                        tags: Vec::new(),
                    },
                    Column {
                        name: "note".into(),
                        kind: ColumnKind::Text,
                        constraints: Vec::new(),
                        tags: Vec::new(),
                    },
                ],
                without_rowid: false,
            }),
        ],
        down: Vec::new(),
        preimage: None,
        flags: Flags::default(),
        author: None,
    })
    .expect("the manifest seals")
}

/// The schema the migration claims to arrive at.
///
/// Derived from the start schema by making the migration's own structural
/// changes to it, rather than authored separately. A hand-written target is a
/// second description of the same intent, and the two drift: the day it did,
/// the oracle would report a divergence about the copy rather than about the
/// engine.
///
/// `ADD COLUMN` appends, so the column is pushed onto the end of the table --
/// the from-scratch arm has to declare its columns in the order SQLite leaves
/// the migrated one in.
fn after_the_migration(start: &Schema) -> Schema {
    let mut target = start.clone();

    let altered = target
        .tables
        .iter_mut()
        .find(|existing| existing.name == FK_TABLE)
        .unwrap_or_else(|| panic!("the every-trait schema carries {FK_TABLE:?}"));
    altered.columns.push(ForgedColumn {
        name: ADDED_COLUMN.into(),
        decl_type: Some(ColumnType::Text),
        constraints: Vec::new(),
    });

    // The builder authors a whole schema rather than a bare table, so the
    // created table is written as a schema of one and folded in.
    let created = schema()
        .table(
            table(CREATED_TABLE)
                .pk_int("id")
                .col("note", ColumnType::Text, []),
        )
        .build()
        .expect("the created table is one SQLite accepts");
    target.tables.extend(created.tables);

    target
        .validate()
        .expect("the post-migration schema is one SQLite accepts");
    target
}

// ---------------------------------------------------------------------------
// Two constructs on one table, through the real rebuild (#398)
// ---------------------------------------------------------------------------

/// A rebuild of a table carrying BOTH a generated column and a foreign key
/// with a referential action.
///
/// Every defect this suite has closed lived on a table carrying one construct,
/// because forger could not spell a table carrying two -- each case declares
/// its construct on its own table and the every-trait schema concatenates
/// them. #398 makes the combination expressible; this is the reason it was
/// worth making.
///
/// The rebuild is where the two meet. `rebuild_dropping_column` inserts
/// preserved generated columns at their declared index and appends
/// reconstructed foreign keys after the column list, so they end up in one
/// body -- and when #387 needed to know whether a preserved column could land
/// after a table-level constraint, that question was answered by a reviewer
/// building the table by hand.
///
/// Each construct is asserted by its own probe, so a failure names which one
/// the rebuild got wrong rather than that something about the table changed.
#[test]
fn the_rebuild_preserves_two_constructs_that_share_a_table() {
    for combination in Combination::all() {
        // The `UNIQUE` column exists only to make SQLite refuse the direct
        // `ALTER`, so the op falls through to the rebuild -- the same lever the
        // other rebuild test here uses, and for the same reason.
        let mut start = combination.schema.clone();
        let child = start
            .tables
            .iter_mut()
            .find(|t| t.name == "combined_child")
            .expect("the combination declares combined_child");
        child.columns.push(ForgedColumn {
            name: REBUILD_FORCER.into(),
            decl_type: Some(ColumnType::Text),
            constraints: vec![ColumnConstraint::Unique(None)],
        });
        start
            .validate()
            .expect("the forced schema is one SQLite accepts");

        let sealed = ChecksummedManifest::seal(Manifest {
            version: 1,
            target_schema: "opaque".into(),
            up: vec![ClassifiedOp::new(Op::DropColumn {
                table: "combined_child".into(),
                column: REBUILD_FORCER.into(),
            })],
            down: Vec::new(),
            preimage: None,
            flags: Flags::default(),
            author: None,
        })
        .expect("the manifest seals");

        let mut fixture = smugglr_forger::fixture::Fixture::new(Backing::Memory).expect("fixture");
        fixture
            .bring_to(smugglr_forger::fixture::Route::Ddl(&start.to_ddl()))
            .expect("the combined schema stands up");
        combination.seed(fixture.conn()).expect("seed");

        let outcome = apply_migration(fixture.conn(), &sealed, &ApplyOptions::default())
            .unwrap_or_else(|error| {
                panic!("{}: the migration did not apply: {error}", combination.name)
            });
        assert_eq!(
            outcome.election,
            Election::Won,
            "{}: the driver has to have won its election, or it applied nothing",
            combination.name
        );

        for (kind, probe) in combination.probes() {
            probe(&combination.schema, fixture.conn()).unwrap_or_else(|error| {
                panic!(
                    "{}: after the real rebuild, {kind:?} did not hold on a table that also \
                     carries the other construct: {error:?}",
                    combination.name
                )
            });
        }
    }
}
