//! forger's differential oracle, with smugglr's own forward apply as the
//! transformation.
//!
//! Everything forger proved before this file existed, it proved about
//! transformations forger itself wrote. Each known-defect case reproduces a
//! defect's *mechanism* by hand and confirms the oracle notices, which is the
//! right way to validate a harness and says nothing about the engine. "forger
//! would have caught #341" was an argument from a reconstruction until
//! something pointed it at the real rebuild. This is that something.
//!
//! The closure handed to [`differential`] calls
//! [`smugglr_core::migrate::driver::apply_migration`] -- the composing forward
//! apply the CLI drives, which verifies the manifest checksum, ensures the
//! ledger schema, assigns and elects a version, lints, and runs the real
//! `migrate::apply::apply_ops` with the pre-image capturer bound to its
//! write-ahead hook. No SQL in this file is executed against the transformed
//! arm; every statement that reaches it was generated by migrate.
//!
//! # The dependency direction
//!
//! forger depends on no smugglr crate and never will
//! (`scripts/check-forger-boundary.py`). This file is the other half of that
//! rule: smugglr's tests depend on forger, dev-only, by path. It is what makes
//! the exclusion set a caller parameter rather than a list forger maintains --
//! [`SyncConfig::default().exclude_tables`] is `config::default_exclude_tables()`
//! reached through the engine's own public surface, and it contains
//! `_smugglr_migrations`, which the driver creates in the transformed arm and
//! which nothing creates in the other. Hand in nothing and every run reports
//! the ledger as a divergence; hand in the engine's list and the same run is
//! silent. forger learns the name from the caller either way.
//!
//! # What this migration deliberately does not do, and which defects that
//! routes around
//!
//! The ops here are additive: `ADD COLUMN` and `CREATE TABLE`. Neither reaches
//! `migrate::apply::rebuild_dropping_column`, which is the only path in the
//! apply engine that *reconstructs* a table rather than asking SQLite to alter
//! it -- and reconstruction is where the open defects live. A manifest that
//! reached it over this schema is red today, by construction and not by
//! accident:
//!
//! * **#341** -- `reconstruct_foreign_keys` reads five of `foreign_key_list`'s
//!   eight columns, so a rebuilt `cascade_child` comes back with its foreign
//!   key and without `ON DELETE CASCADE`. [`Trait::ForeignKeyWithAction`].
//! * **#342** -- `PRAGMA table_info` does not return generated columns at all,
//!   so a rebuild never sees them and cannot copy them.
//!   [`Trait::GeneratedVirtual`] and [`Trait::GeneratedStored`].
//!
//! Both are open and neither is this file's to fix (#377 is the wiring; #341 is
//! sequenced behind it, to be proven *by* it). So this test asserts what the
//! additive path preserves and claims nothing about the rebuild. **Do not read
//! a green run here as coverage of the rebuild.** The measurement of the
//! rebuild belongs in #341's and #342's own PRs, where a red-to-green flip is
//! the evidence the fix works; a test committed here asserting today's red
//! would go green on a defect and fail when the defect is fixed.
//!
//! One more thing this manifest does not reach, for the same reason: both ops
//! are structurally additive, so the lint never classifies a destructive op and
//! the pre-image capturer bound to the apply loop's write-ahead hook captures
//! nothing. The destructive lane runs in the closure and is inert.
//!
//! A caveat survives even for what is covered: the referential-action probe
//! exercises the `ON DELETE` half only. `ON UPDATE` has no probe (#374) and
//! `RESTRICT` is behaviourally identical to the `NO ACTION` default under
//! immediate enforcement. forger's own boundary output states both.

use rusqlite::Connection;

use smugglr_core::config::SyncConfig;
use smugglr_core::migrate::driver::{apply_migration, ApplyOptions};
use smugglr_core::migrate::ledger::Election;
use smugglr_core::migrate::{
    ChecksummedManifest, ClassifiedOp, Column, ColumnKind, Constraint, Flags, Manifest, Op,
};

use smugglr_forger::census::every_trait_schema;
use smugglr_forger::error::BoxError;
use smugglr_forger::fixture::Backing;
use smugglr_forger::oracle::{differential, Outcome};
use smugglr_forger::schema::builder::{schema, table};
// Renamed on import: `smugglr_core::migrate::Column` is a manifest op's column
// and this one is a schema model's. Two `Column`s in one file is a reader
// tripping over which layer they are in.
use smugglr_forger::schema::{Column as ForgedColumn, ColumnType, Schema, Trait};

/// The table in forger's every-trait schema that carries the foreign key with a
/// referential action -- the #341 table. The migration adds a column to *this*
/// one rather than to an inert table, so the apply runs over a table whose
/// behaviour the oracle is watching.
const FK_TABLE: &str = "cascade_child";

/// The column the migration adds. Named for what it is, since it lands in a
/// schema whose other column names are forger's.
const ADDED_COLUMN: &str = "migration_note";

/// The table the migration creates. It carries no trait; it is here so the
/// oracle's table inventory has something to compare that only exists because
/// migrate ran.
const CREATED_TABLE: &str = "migration_audit";

// ---------------------------------------------------------------------------
// The test
// ---------------------------------------------------------------------------

/// A real migration, applied by the real driver, over a schema carrying all
/// eight traits.
///
/// Both backings, because the oracle's arms are stood up per backing and the
/// CLI's apply reaches a file while these assertions are cheap enough to make
/// twice.
#[test]
fn the_real_apply_path_preserves_every_trait_it_migrates_over() {
    for backing in Backing::ALL {
        let start = every_trait_schema();
        let target = after_the_migration(&start);
        let sealed = the_migration();

        // The engine's own list, reached through the engine's own public
        // surface: `SyncConfig::default().exclude_tables` *is*
        // `config::default_exclude_tables()`.
        let ignore = SyncConfig::default().exclude_tables;

        let mut applied = Vec::new();
        let mut transform = |conn: &mut Connection| -> Result<(), BoxError> {
            applied.push(apply_migration(conn, &sealed, &ApplyOptions::default())?);
            Ok(())
        };

        let report = differential(backing, &start, &target, &mut transform, &ignore)
            .unwrap_or_else(|error| panic!("{backing:?}: the migration did not run: {error}"));

        // A migration that did not apply would leave both arms holding on every
        // trait, so the run has to be shown to have happened before the silence
        // is read as a result. The election is the driver's own word for it.
        let outcome = match applied.as_slice() {
            [outcome] => outcome,
            other => panic!("{backing:?}: the transformation ran {} times", other.len()),
        };
        assert_eq!(
            outcome.election,
            Election::Won,
            "{backing:?}: the driver has to have won its election, or it applied nothing"
        );
        assert_eq!(
            outcome.classifications.len(),
            sealed.manifest.up.len(),
            "{backing:?}: every op should have been linted and applied"
        );

        // Two arms that broke identically do not diverge, so "no divergence" is
        // also what a bad target schema or a mislocated probe produces. Without
        // this, every comparison below is an agreement between two wrong
        // answers.
        assert!(
            report.baseline_is_sound(),
            "{backing:?}: these did not hold in the arm built from the target schema, so nothing \
             compared against it means anything: {:?}",
            report.unsound_baseline()
        );

        for observed in &report.traits {
            assert_eq!(
                observed.transformed,
                Outcome::Held,
                "{backing:?}: {:?} did not hold after the real apply",
                observed.kind
            );
        }

        assert_eq!(
            report.divergences(),
            Vec::new(),
            "{backing:?}: the migrated database and the one built from the target schema \
             answered differently"
        );

        // Named rather than left to the loop above, because this is the trait
        // the additive path is being claimed for: the table the migration
        // altered is the table whose cascade the probe deletes through.
        assert_eq!(
            report.for_trait(Trait::ForeignKeyWithAction).transformed,
            Outcome::Held,
            "{backing:?}: ADD COLUMN on {FK_TABLE:?} lost its referential action"
        );
    }
}

// ---------------------------------------------------------------------------
// The migration
// ---------------------------------------------------------------------------

/// The manifest, sealed exactly as the CLI would read one off disk.
///
/// `version: 1` is the generator's hardcoded value and the driver overrides it;
/// `target_schema` is opaque for 0.5.0. Both ops are structurally additive, so
/// the lint passes them and no pre-image is required.
fn the_migration() -> ChecksummedManifest {
    ChecksummedManifest::seal(Manifest {
        version: 1,
        target_schema: "opaque".into(),
        up: vec![
            ClassifiedOp::new(Op::AddColumn {
                table: FK_TABLE.into(),
                column: Column {
                    name: ADDED_COLUMN.into(),
                    kind: ColumnKind::Text,
                    constraints: Vec::new(),
                    tags: Vec::new(),
                },
            }),
            ClassifiedOp::new(Op::CreateTable {
                table: CREATED_TABLE.into(),
                columns: vec![
                    Column {
                        name: "id".into(),
                        kind: ColumnKind::Int,
                        constraints: vec![Constraint::Pk],
                        tags: Vec::new(),
                    },
                    Column {
                        name: "note".into(),
                        kind: ColumnKind::Text,
                        constraints: Vec::new(),
                        tags: Vec::new(),
                    },
                ],
                without_rowid: false,
            }),
        ],
        down: Vec::new(),
        preimage: None,
        flags: Flags::default(),
        author: None,
    })
    .expect("the manifest seals")
}

/// The schema the migration claims to arrive at.
///
/// Derived from the start schema by making the migration's own structural
/// changes to it, rather than authored separately. A hand-written target is a
/// second description of the same intent, and the two drift: the day it did,
/// the oracle would report a divergence about the copy rather than about the
/// engine.
///
/// `ADD COLUMN` appends, so the column is pushed onto the end of the table --
/// the from-scratch arm has to declare its columns in the order SQLite leaves
/// the migrated one in.
fn after_the_migration(start: &Schema) -> Schema {
    let mut target = start.clone();

    let altered = target
        .tables
        .iter_mut()
        .find(|existing| existing.name == FK_TABLE)
        .unwrap_or_else(|| panic!("the every-trait schema carries {FK_TABLE:?}"));
    altered.columns.push(ForgedColumn {
        name: ADDED_COLUMN.into(),
        decl_type: Some(ColumnType::Text),
        constraints: Vec::new(),
    });

    // The builder authors a whole schema rather than a bare table, so the
    // created table is written as a schema of one and folded in.
    let created = schema()
        .table(
            table(CREATED_TABLE)
                .pk_int("id")
                .col("note", ColumnType::Text, []),
        )
        .build()
        .expect("the created table is one SQLite accepts");
    target.tables.extend(created.tables);

    target
        .validate()
        .expect("the post-migration schema is one SQLite accepts");
    target
}
