#!/usr/bin/env python3
"""Generate seed.sql for the Westwind sample database.

Deterministic: the same script always writes the same rows and the same ids,
so output captured against this database is stable across machines. Ids are
UUIDv7 (a millisecond timestamp in the top 48 bits, then version and variant
bits, then random bits from a seeded generator), which is the key shape
smugglr requires. updated_at is unix seconds derived from the row's date.
"""

import random
from datetime import date, datetime, timedelta, timezone

rng = random.Random(0x57455354)  # "WEST"
EPOCH_MS = int(datetime(2025, 1, 6, tzinfo=timezone.utc).timestamp() * 1000)
counter = [0]


def uuid7() -> str:
    counter[0] += 1
    ms = EPOCH_MS + counter[0] * 977
    rand_a = rng.getrandbits(12)
    rand_b = rng.getrandbits(62)
    hi = (ms << 80) | (0x7 << 76) | (rand_a << 64)
    lo = (0b10 << 62) | rand_b
    h = f"{(hi | lo):032x}"
    return f"{h[:8]}-{h[8:12]}-{h[12:16]}-{h[16:20]}-{h[20:]}"


def ts(d: date) -> int:
    return int(datetime(d.year, d.month, d.day, 9, 0, tzinfo=timezone.utc).timestamp())


def q(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


out = ["-- Westwind seed data. Generated by generate.py; do not edit by hand.", "BEGIN;"]


def insert(table, cols, rows):
    out.append(f"INSERT INTO {table} ({', '.join(cols)}) VALUES")
    out.append(",\n".join("  (" + ", ".join(q(v) for v in r) + ")" for r in rows) + ";")


base = date(2025, 1, 6)

categories = [
    ("Wine", "Arbor gold and Dornish red, landed at night and never taxed"),
    ("Steel", "Castle-forged blades and the odd Valyrian piece, provenance unasked"),
    ("Cloth", "Myrish lace, Lysene silk, Tyroshi dye"),
    ("Onions", "The founding cargo. Sacks of them, still"),
    ("Salt fish", "Sistermen cod and Blackwater herring, barreled"),
    ("Dreamwine", "Lysene, by the cask, for those who can pay"),
    ("Glass", "Dragonglass off Dragonstone and Myrish far-eyes"),
    ("Spice", "Saffron, pepper, and cloves that never saw a customs house"),
]
cat_rows = [(uuid7(), n, d, ts(base)) for n, d in categories]
insert("categories", ["id", "name", "description", "updated_at"], cat_rows)
cat_id = {n: r[0] for n, r in zip([c[0] for c in categories], cat_rows)}

suppliers = [
    ("Redwyne Cellars, Back Door", "a cellarer who does not sign", "Ryamsport", "The Arbor"),
    ("Qohor Smiths' Guild", "Tobho Mott", "Qohor", "Essos"),
    ("Myrish Lace Consortium", "Doreah", "Myr", "Essos"),
    ("Flea Bottom Onion Yard", "Marya Seaworth", "King's Landing", "The Crownlands"),
    ("Sisterton Salthouse", "Godric Borrell", "Sisterton", "The Three Sisters"),
    ("Lysene Vintners", "Lysono Maar", "Lys", "Essos"),
    ("Dragonstone Quarry", "Maester Cressen", "Dragonstone", "The Crownlands"),
    ("Volantene Spice Company", "Malaquo Maegyr", "Volantis", "Essos"),
]
sup_rows = [(uuid7(), c, p, city, reg, ts(base)) for c, p, city, reg in suppliers]
insert("suppliers", ["id", "company", "contact", "city", "region", "updated_at"], sup_rows)
sup_id = {s[0]: r[0] for s, r in zip(suppliers, sup_rows)}

products = [
    ("Arbor Gold, Untaxed", "Redwyne Cellars, Back Door", "Wine", "cask", 48.0, 120),
    ("Dornish Red, Untaxed", "Redwyne Cellars, Back Door", "Wine", "cask", 36.0, 200),
    ("Sour Red of the Reach", "Redwyne Cellars, Back Door", "Wine", "cask", 18.0, 340),
    ("Castle-forged Longsword", "Qohor Smiths' Guild", "Steel", "each", 240.0, 24),
    ("Valyrian Steel Dagger, No Questions", "Qohor Smiths' Guild", "Steel", "each", 4200.0, 1),
    ("Myrish Lace", "Myrish Lace Consortium", "Cloth", "bolt", 62.0, 90),
    ("Lysene Silk", "Myrish Lace Consortium", "Cloth", "bolt", 88.0, 40),
    ("Onions, Yellow", "Flea Bottom Onion Yard", "Onions", "sack", 6.0, 900),
    ("Onions, Red", "Flea Bottom Onion Yard", "Onions", "sack", 7.0, 700),
    ("Onions, Pickled", "Flea Bottom Onion Yard", "Onions", "barrel", 15.0, 260),
    ("Salt Cod", "Sisterton Salthouse", "Salt fish", "barrel", 27.0, 400),
    ("Blackwater Herring", "Sisterton Salthouse", "Salt fish", "barrel", 19.0, 380),
    ("Dreamwine", "Lysene Vintners", "Dreamwine", "cask", 310.0, 12),
    ("Sweetsleep, Sealed", "Lysene Vintners", "Dreamwine", "vial", 120.0, 30),
    ("Dragonglass, Rough", "Dragonstone Quarry", "Glass", "crate", 95.0, 40),
    ("Dragonglass Arrowheads", "Dragonstone Quarry", "Glass", "score", 30.0, 260),
    ("Myrish Far-eye", "Dragonstone Quarry", "Glass", "each", 400.0, 6),
    ("Saffron", "Volantene Spice Company", "Spice", "ounce", 14.0, 500),
    ("Black Pepper", "Volantene Spice Company", "Spice", "pound", 9.0, 900),
    ("Wildfire, Sealed Jar", "Volantene Spice Company", "Spice", "jar", 900.0, 0),
]
prod_rows = []
for i, (n, s, c, u, price, stock) in enumerate(products):
    prod_rows.append((uuid7(), n, sup_id[s], cat_id[c], u, price, stock, 1 if stock == 0 else 0, ts(base)))
insert("products", ["id", "name", "supplier_id", "category_id", "unit", "unit_price", "in_stock", "discontinued", "updated_at"], prod_rows)

customers = [
    ("DRAGN", "Dragonstone Garrison", "Stannis Baratheon", "Lord of Dragonstone", "Dragonstone", "The Crownlands"),
    ("STORM", "Storm's End, Under Siege", "Cortnay Penrose", "Castellan", "Storm's End", "The Stormlands"),
    ("WINTF", "House Stark of Winterfell", "Vayon Poole", "Steward", "Winterfell", "The North"),
    ("CASTR", "House Lannister of Casterly Rock", "Tyrion Lannister", "Master of Coin", "Lannisport", "The Westerlands"),
    ("HIGHG", "House Tyrell of Highgarden", "Olenna Tyrell", "Lady of Highgarden", "Highgarden", "The Reach"),
    ("SUNSP", "House Martell of Sunspear", "Doran Martell", "Prince of Dorne", "Sunspear", "Dorne"),
    ("EYRIE", "House Arryn of the Eyrie", "Nestor Royce", "Keeper of the Gates", "Gulltown", "The Vale"),
    ("PYKE", "House Greyjoy of Pyke", "Asha Greyjoy", "Captain", "Lordsport", "The Iron Islands"),
    ("RIVER", "House Tully of Riverrun", "Edmure Tully", "Lord of Riverrun", "Riverrun", "The Riverlands"),
    ("BEARI", "House Mormont of Bear Island", "Maege Mormont", "Lady of Bear Island", "Bear Island", "The North"),
    ("WHITE", "House Manderly of White Harbor", "Wyman Manderly", "Lord of White Harbor", "White Harbor", "The North"),
    ("TWINS", "House Frey of the Crossing", "Walder Frey", "Lord of the Crossing", "The Twins", "The Riverlands"),
    ("OLDTN", "House Hightower of Oldtown", "Leyton Hightower", "Voice of Oldtown", "Oldtown", "The Reach"),
    ("ARBOR", "House Redwyne of the Arbor", "Paxter Redwyne", "Lord of the Arbor", "Ryamsport", "The Reach"),
    ("TARTH", "House Tarth of Evenfall", "Selwyn Tarth", "Evenstar", "Evenfall Hall", "The Stormlands"),
    ("CROWN", "The Red Keep, Kitchens", "Petyr Baelish", "Master of Coin", "King's Landing", "The Crownlands"),
    ("WATCH", "The Night's Watch", "Bowen Marsh", "Lord Steward", "Castle Black", "The Wall"),
    ("CITAD", "The Citadel", "Archmaester Marwyn", "Archmaester", "Oldtown", "The Reach"),
    ("BRAAV", "The Iron Bank", "Tycho Nestoris", "Envoy", "Braavos", "Essos"),
    ("PENTS", "Illyrio Mopatis", "Illyrio Mopatis", "Magister", "Pentos", "Essos"),
    ("SISTR", "Breakwater Castle", "Godric Borrell", "Lord of Sweetsister", "Sisterton", "The Three Sisters"),
    ("GULLT", "Gulltown Harbormaster", "Gerold Grafton", "Lord of Gulltown", "Gulltown", "The Vale"),
    ("DUSKN", "Duskendale", "Rykker", "Lord of Duskendale", "Duskendale", "The Crownlands"),
    ("MAIDN", "Maidenpool", "William Mooton", "Lord of Maidenpool", "Maidenpool", "The Riverlands"),
    ("SALTP", "Saltpans", "Quincy Cox", "Ser", "Saltpans", "The Riverlands"),
    ("GREEN", "The Merling King, Inn", "the innkeep", "Innkeep", "Gulltown", "The Vale"),
    ("BLKWT", "Blackwater Rush, East Bank", "Sallor the Bald", "Factor", "King's Landing", "The Crownlands"),
    ("FLEAB", "Flea Bottom Pot Shops", "Umma", "Cook", "King's Landing", "The Crownlands"),
    ("LYSEN", "Lys, Harbor Guild", "Lysono Maar", "Magister", "Lys", "Essos"),
    ("TYROS", "Tyrosh, Dyers' Hall", "the Archon's factor", "Factor", "Tyrosh", "Essos"),
    ("MYRCT", "Myr, Glassblowers", "a magister", "Magister", "Myr", "Essos"),
    ("QUARTH", "Qarth, Thirteen", "Xaro Xhoan Daxos", "Merchant Prince", "Qarth", "Essos"),
    ("VOLAN", "Volantis, Old Blood", "Malaquo Maegyr", "Triarch", "Volantis", "Essos"),
    ("STEPS", "Bloodstone Anchorage", "the Lord of the Waters", "Pirate Lord", "Bloodstone", "The Stepstones"),
    ("GREYS", "Greywater Watch", "Howland Reed", "Lord of Greywater Watch", "Greywater Watch", "The Neck"),
    ("SEAGD", "Seagard Watchtower", "Jason Mallister", "Lord of Seagard", "Seagard", "The Riverlands"),
    ("DREAD", "The Dreadfort", "Roose Bolton", "Lord of the Dreadfort", "The Dreadfort", "The North"),
    ("CLAWI", "Claw Isle", "Ardrian Celtigar", "Lord of Claw Isle", "Claw Isle", "The Crownlands"),
    ("KARHD", "Karhold", "Rickard Karstark", "Lord of Karhold", "Karhold", "The North"),
    ("HARRN", "Harrenhal", "the castellan", "Castellan", "Harrenhal", "The Riverlands"),
]
cust_rows = [(uuid7(), code, co, ct, ti, city, reg, ts(base)) for code, co, ct, ti, city, reg in customers]
insert("customers", ["id", "code", "company", "contact", "title", "city", "region", "updated_at"], cust_rows)

employees = [
    ("DAVOS", "Seaworth", "Davos", "Onion Knight, Proprietor", None, "Cape Wrath"),
    ("SALLA", "Saan", "Salladhor", "Pirate, Partner", "DAVOS", "Lys"),
    ("DALE", "Seaworth", "Dale", "Captain, Wraith", "DAVOS", "Cape Wrath"),
    ("ALLRD", "Seaworth", "Allard", "Captain, Lady Marya", "DAVOS", "Cape Wrath"),
    ("MATTH", "Seaworth", "Matthos", "Clerk, Black Betha", "DAVOS", "Dragonstone"),
    ("MARIC", "Seaworth", "Maric", "Oarmaster, Fury", "DAVOS", "Cape Wrath"),
    ("KHORA", "Sathmantes", "Khorane", "Captain, Shayala's Dance", "SALLA", "Lys"),
    ("SALLO", "the Bald", "Sallor", "Factor, Blackwater", "SALLA", "King's Landing"),
    ("LOTHR", "Brune", "Lothor", "Purser", "DAVOS", "Dragonstone"),
]
emp_ids = {code: uuid7() for code, *_ in employees}
emp_rows = [(emp_ids[code], code, ln, fn, ti, emp_ids[rep] if rep else None, city, ts(base)) for code, ln, fn, ti, rep, city in employees]
insert("employees", ["id", "code", "last_name", "first_name", "title", "reports_to", "city", "updated_at"], emp_rows)

shippers = [("Black Betha", "Blackwater quay, berth 3, after dark"), ("Lady Marya", "Cape Wrath, the cove"), ("Shayala's Dance", "Lys, ask for the Lysene")]
ship_rows = [(uuid7(), c, p, ts(base)) for c, p in shippers]
insert("shippers", ["id", "company", "phone", "updated_at"], ship_rows)

order_rows, detail_rows = [], []
for i in range(320):
    od = base + timedelta(days=rng.randint(0, 360))
    req = od + timedelta(days=rng.choice([7, 14, 21, 28]))
    shipped = None if rng.random() < 0.12 else od + timedelta(days=rng.randint(1, 20))
    cust = rng.choice(cust_rows)
    emp = rng.choice(emp_rows)
    shp = rng.choice(ship_rows)
    oid = uuid7()
    order_rows.append((oid, cust[0], emp[0], shp[0], od.isoformat(), req.isoformat(), shipped.isoformat() if shipped else None, round(rng.uniform(2, 180), 2), cust[5], cust[6], ts(shipped or od)))
    for p in rng.sample(prod_rows, rng.randint(1, 4)):
        disc = rng.choice([0, 0, 0, 0.05, 0.1, 0.15])
        detail_rows.append((uuid7(), oid, p[0], p[5], rng.randint(1, 40), disc, ts(shipped or od)))
insert("orders", ["id", "customer_id", "employee_id", "shipper_id", "order_date", "required_date", "shipped_date", "freight", "ship_city", "ship_region", "updated_at"], order_rows)
insert("order_details", ["id", "order_id", "product_id", "unit_price", "quantity", "discount", "updated_at"], detail_rows)

out.append("COMMIT;")
open("seed.sql", "w").write("\n".join(out) + "\n")
print(f"categories {len(cat_rows)}, suppliers {len(sup_rows)}, products {len(prod_rows)}, customers {len(cust_rows)}, employees {len(emp_rows)}, shippers {len(ship_rows)}, orders {len(order_rows)}, order_details {len(detail_rows)}")
